### ISSUE TITLE
Missing commas on U+0218..U+021B

### ISSUE THREAD

**Issue by dscorbett** [WCYS-Co/HauoraSans#18]
In version 1.000, U+0218 LATIN CAPITAL LETTER S WITH COMMA BELOW through U+021B LATIN SMALL LETTER T WITH COMMA BELOW are missing their commas.

**Comment by wayne-shih** [comment]
@dscorbett this has been addressed in the latest [`v1.001`](https://github.com/WCYS-Co/HauoraSans/releases/tag/v1.001) release 
thanks for raising the issue! 🙌

**Comment by wayne-shih** [comment]
this was fixed properly on release [1.003](https://github.com/WCYS-Co/Hauora-Sans/releases/tag/v1.003)
